AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/AbcSize:
  CountRepeatedAttributes: false

Gemspec/RequireMFA:
  Enabled: false
